### ISSUE TITLE
Tuple BIFs

### ISSUE THREAD

**Issue by archseer** [archseer/enigma#11]
- [x] bif erlang:make_tuple/2
- [x] bif erlang:append_element/2
- [x] bif erlang:make_tuple/3
- [x] bif erlang:setelement/3
- [x] bif erlang:tuple_to_list/1

Most of these can be done in a very similar way to the tup macros: https://github.com/archseer/enigma/blob/f2fbd9576de4f2b9dc663ddd86baa045c65a9f9b/src/macros/mod.rs#L6-L11

For setelement/any functions that copy the old tuple, we can 1) allocate a new tuple, 2) use [std::ptr::copy_nonoverlapping](https://doc.rust-lang.org/beta/std/ptr/fn.copy_nonoverlapping.html) to do a fast `memcpy` of the old tuple to the new tuple 3) set the new elements

**Comment by RyanSiu1995** [comment]
I will take it then. 
I don't have right to self-assign lol.

**Comment by archseer** [comment]
Closed by #30 ! 🎊
