### ISSUE TITLE
Separate the bif implementation and bif.rs

### ISSUE THREAD

**Issue by RyanSiu1995** [archseer/enigma#25]
Currently, some of the bif implementation is written in bif.rs and some of them are in bif folder.
We can gather them into bif folder instead. 
Then, bif.rs can be served as an index of the current bif and file in bif are the implementation with unit tests.

- [ ] erlang function
- [ ] math function
- [ ] list function

**Comment by archseer** [comment]
Finished in master. I kept a few functions there for now as a "staging area"
