### ISSUE TITLE
Fail to update submodule otp

### ISSUE THREAD

**Issue by yima77** [archseer/enigma#34]
I am getting this when I follow the instruction to update otp. Do we have a workaround?

~/play/enigma$ git submodule update 
fatal: reference is not a tree: 7bcc044cb00b8dfb8eb2eb220dbda8a395af72a7
Unable to checkout '7bcc044cb00b8dfb8eb2eb220dbda8a395af72a7' in submodule path 'otp'

**Comment by archseer** [comment]
@yima77 Sorry about that! It was pointing to a commit that I made locally but wasn't upstream. I've pushed https://github.com/archseer/enigma/commit/59a8c979ec02aa732607dbce4e96a0aa517a7b19 that should fix it. Let me know if you need any help building the source!

**Comment by yima77** [comment]
Problem solved. I am now able to pull submodule otp. Thx!
