### ISSUE TITLE
Fail to build otp due to missing libraries

### ISSUE THREAD

**Issue by yima77** [archseer/enigma#35]
After Issue #34 was resolved, I was able to update otp and start the build. However, the build failed due to the following errors:

=== Entering application tools
make[3]: Entering directory '/home/yima/play/enigma/otp/lib/tools/c_src'
 MAKE   opt
make[4]: Entering directory '/home/yima/play/enigma/otp/lib/tools/c_src'
 CC     ../obj/x86_64-unknown-linux-gnu/opt/emem/erl_memory.o
 CC     ../obj/x86_64-unknown-linux-gnu/opt/emem/erl_memory_trace_block_table.o
 LD     ../bin/x86_64-unknown-linux-gnu/emem
/usr/bin/ld: cannot find -lerts_r
/usr/bin/ld: cannot find -lethread
/usr/bin/ld: cannot find -lerts_internal_r
collect2: error: ld returned 1 exit status
x86_64-unknown-linux-gnu/Makefile:182: recipe for target '../bin/x86_64-unknown-linux-gnu/emem' failed
make[4]: *** [../bin/x86_64-unknown-linux-gnu/emem] Error 1

**Comment by archseer** [comment]
Hmm, try running `./otp_build boot` first which will compile the regular BEAM, then `make libs` and `make local_setup`. So:

```
./otp_build autoconf
./otp_build configure
./otp_build boot
make libs
make local_setup
```

BEAM's build system is really finicky to get working, but luckily I'm almost done with the work necessary to run the erlang compiler via enigma -- then we won't need to use OTP build tools anymore.

**Comment by yima77** [comment]
After running ./otp_build boot, the build was successful. Please update README.md to include this step so others won't encounter the same issue as I did. Thx!
