### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by chrisalmeida** [archseer/enigma#37]
Hi @archseer,

I'm very new to Rust (familiar with Erlang), so please forgive me.
I am attempting to compile Enigma and receiving the following message`to use a constant of type value::Term in a pattern, value::Term must be annotated with #[derive(PartialEq, Eq)]`.
From what I can tell this seems to be related to the `APPLY_2` const but again, I'm not familiar at all with Rust.
Any idea what is causing this?

rustc 1.39.0-nightly (72b2abfd6 2019-08-29)
rustup 1.18.3 (435397f48 2019-05-22)
cargo 1.39.0-nightly (22f7dd049 2019-08-27)

**Comment by archseer** [comment]
Hi! It's a bug in rust nightly sadly: https://github.com/rust-lang/rust/issues/63479

They'll hopefully resolve it in a couple of weeks. I'll push a workaround meanwhile
