### ISSUE TITLE
Rebase problem in maps

### ISSUE THREAD

**Issue by RyanSiu1995** [archSeer/enigma#5]
Hi @archSeer,
it seems the code in maps is being rebased. 
Some of the implementation is cleared. Can you please help fix the problem?
Thank you!

**Comment by archSeer** [comment]
What commits are missing? I'll take a look in a few hours

**Comment by archSeer** [comment]
Ah I see it now, my rebase was bad, will fix! Feel free to just drop my last commit on your branch

**Comment by archSeer** [comment]
I'll stop committing to master and open PRs myself now as well

**Comment by RyanSiu1995** [comment]
I just rebase from the master after you have fixed it. I wait for you :)

**Comment by archSeer** [comment]
Fixed with f834d4862ba5b94dc382d07cb4eb191cbe2727a1
